/**
 * Converts an image to ASCII art and writes src/generated/ascii-art.ts
 * Usage: pnpm gen:ascii [path/to/image.jpg]
 */
import { Jimp } from 'jimp'
import { writeFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const CHARS = ' .,:;i1tfLCG08@'
const COLS = 100
const ASPECT_CORRECTION = 0.45 // terminal chars are ~2x taller than wide

async function imageToAscii(imagePath: string): Promise<string> {
  const img = await Jimp.read(imagePath)

  const rows = Math.round((COLS * img.height) / img.width * ASPECT_CORRECTION)
  img.resize({ w: COLS, h: rows })
  img.greyscale()

  const lines: string[] = []
  for (let y = 0; y < rows; y++) {
    let line = ''
    for (let x = 0; x < COLS; x++) {
      const color = img.getPixelColor(x, y) as unknown as number
      const r = (color >>> 24) & 0xff
      const brightness = r / 255
      const index = Math.floor(brightness * (CHARS.length - 1))
      line += CHARS[index]
    }
    lines.push(line)
  }
  return lines.join('\n')
}

const inputPath = process.argv[2] ?? resolve(__dirname, '../public/headshot.jpg')
const outputPath = resolve(__dirname, '../src/generated/ascii-art.ts')

try {
  console.log(`Reading: ${inputPath}`)
  const art = await imageToAscii(inputPath)
  const content = `// Generated by scripts/generate-ascii.ts — run \`pnpm gen:ascii public/headshot.jpg\` to regenerate\nexport const ASCII_ART = \`\n${art}\n\`\n`
  writeFileSync(outputPath, content, 'utf-8')
  console.log(`Written: ${outputPath}`)
} catch (err) {
  console.error('Failed to generate ASCII art:', err)
  process.exit(1)
}
